// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Test.proto

package com.violin.grpc.demo.api;

public final class DemoGrpcService {
  private DemoGrpcService() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_UserInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_UserInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PersonRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PersonRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PersonResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PersonResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PersonRequest1_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PersonRequest1_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PersonResponse2_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PersonResponse2_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\nTest.proto\"C\n\010UserInfo\022\n\n\002id\030\001 \001(\005\022\014\n\004" +
      "name\030\002 \001(\t\022\013\n\003sex\030\003 \001(\010\022\020\n\010isMember\030\004 \001(" +
      "\010\"\033\n\rPersonRequest\022\n\n\002id\030\001 \001(\005\";\n\016Person" +
      "Response\022\014\n\004name\030\001 \001(\t\022\033\n\010userInfo\030\002 \001(\013" +
      "2\t.UserInfo\"\020\n\016PersonRequest1\"\021\n\017PersonR" +
      "esponse22{\n\017PersonSearchRpc\0220\n\013getUserIn" +
      "fo\022\016.PersonRequest\032\017.PersonResponse\"\000\0226\n" +
      "\017getUserInfoPojo\022\017.PersonRequest1\032\020.Pers" +
      "onResponse2\"\000B3\n\030com.violin.grpc.demo.ap" +
      "iB\017DemoGrpcServiceP\001\242\002\003RTGb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_UserInfo_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_UserInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_UserInfo_descriptor,
        new String[] { "Id", "Name", "Sex", "IsMember", });
    internal_static_PersonRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_PersonRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PersonRequest_descriptor,
        new String[] { "Id", });
    internal_static_PersonResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_PersonResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PersonResponse_descriptor,
        new String[] { "Name", "UserInfo", });
    internal_static_PersonRequest1_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_PersonRequest1_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PersonRequest1_descriptor,
        new String[] { });
    internal_static_PersonResponse2_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_PersonResponse2_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PersonResponse2_descriptor,
        new String[] { });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
