// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Test.proto

package com.violin.grpc.demo.api;

/**
 * Protobuf type {@code PersonResponse2}
 */
public final class PersonResponsePojo {
  private int id;
  private UserInfoPojo userInfoPojo;

  public int getId() {
    return id;
  }

  public void setId(int id) {
    this.id = id;
  }

  public UserInfoPojo getUserInfoPojo() {
    return userInfoPojo;
  }

  public void setUserInfoPojo(UserInfoPojo userInfoPojo) {
    this.userInfoPojo = userInfoPojo;
  }
}

