// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Test.proto

package com.violin.grpc.demo.api;

/**
 * Protobuf type {@code PersonRequest1}
 */
public final class PersonRequestPojo {
        private int id;

        public int getId() {
          return id;
        }

        public void setId(int id) {
          this.id = id;
        }
}

