// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Test.proto

package com.violin.grpc.demo.api;

public interface PersonResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:PersonResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   * @return The name.
   */
  String getName();
  /**
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>.UserInfo userInfo = 2;</code>
   * @return Whether the userInfo field is set.
   */
  boolean hasUserInfo();
  /**
   * <code>.UserInfo userInfo = 2;</code>
   * @return The userInfo.
   */
  UserInfo getUserInfo();
  /**
   * <code>.UserInfo userInfo = 2;</code>
   */
  UserInfoOrBuilder getUserInfoOrBuilder();
}
